name: Lint

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  workflow_run:
    workflows: ["Merging to documentation"]
    types:
      - completed


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  eslint:
    name: runner / eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: reviewdog/action-eslint@v1
        with:
          reporter: github-pr-review # Change reporter.
          eslint_flags: 'src/'
