# This is a basic workflow to help you get started with Actions

name: Testing

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  workflow_run:
    workflows: ["Merging to documentation"]
    types:
      - completed


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 12
          cache: 'npm'
      - run: npm ci eslint
      - run: npm test

      - name: Set Git config
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"
  
#       - name: Running compodoc
#         run: |
#           npm install -g @compodoc/compodoc
#           npx compodoc -p tsconfig.doc.json -d ./docs
          

      
      - name: Uploading to git
        run: |
          git checkout documentation
          git add * 
          git commit -m "Updating github pages"
          git push
